USE [master]
GO

/****** Object:  Database [MyTestDB2]    Script Date: 1/3/2020 2:44:16 AM ******/


--DROP DATABASE [MyTestDB2]
--GO

/****** Object:  Database [MyTestDB2]    Script Date: 1/3/2020 2:44:16 AM ******/
CREATE DATABASE [MyTestDB2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyTestDB2', FILENAME = N'/var/opt/mssql/data/MyTestDB2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyTestDB2_log', FILENAME = N'/var/opt/mssql/data/MyTestDB2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MyTestDB2] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyTestDB2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyTestDB2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyTestDB2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyTestDB2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyTestDB2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyTestDB2] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyTestDB2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyTestDB2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyTestDB2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyTestDB2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyTestDB2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyTestDB2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyTestDB2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyTestDB2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyTestDB2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyTestDB2] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyTestDB2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyTestDB2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyTestDB2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyTestDB2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyTestDB2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyTestDB2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyTestDB2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyTestDB2] SET RECOVERY FULL 
GO

ALTER DATABASE [MyTestDB2] SET  MULTI_USER 
GO

ALTER DATABASE [MyTestDB2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyTestDB2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyTestDB2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyTestDB2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyTestDB2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyTestDB2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyTestDB2] SET  READ_WRITE 
GO



--Create tables

CREATE TABLE [dbo].[Product](
	[ProdId] [int] IDENTITY(1,1) NOT NULL,
	[ProdName] [varchar](50) NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[ProdId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventory](
	[InvId] [int] IDENTITY(3,1) NOT NULL,
	[ProdId] [int] NULL,
	[Desc] [nvarchar](50) NULL,
	[ProdQuant] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Inventory] ADD  CONSTRAINT [PK_Inventory] PRIMARY KEY CLUSTERED 
(
	[InvId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, 
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Inventory] ADD  CONSTRAINT [DF_Inventory_WarehouseID]  DEFAULT ((1)) FOR [Desc]
GO
ALTER TABLE [dbo].[Inventory]  WITH CHECK ADD  CONSTRAINT [FK_Inventory_Product] FOREIGN KEY([ProdId])
REFERENCES [dbo].[Product] ([ProdId])
GO
ALTER TABLE [dbo].[Inventory] CHECK CONSTRAINT [FK_Inventory_Product]
GO